/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#2d3133',
        'on-secondary-fixed-variant': '#004395',
        'surface-container-lowest': '#ffffff',
        'outline': '#76777d',
        'on-primary-container': '#7c839b',
        'surface-bright': '#f7f9fb',
        'on-tertiary-fixed': '#0b1c30',
        'secondary-fixed-dim': '#adc6ff',
        'primary-fixed-dim': '#bec6e0',
        'surface-container-highest': '#e0e3e5',
        'on-background': '#191c1e',
        'surface-container-low': '#f2f4f6',
        'primary-container': '#131b2e',
        'background': '#f7f9fb',
        'secondary-fixed': '#d8e2ff',
        'on-error': '#ffffff',
        'inverse-primary': '#bec6e0',
        'inverse-on-surface': '#eff1f3',
        'on-primary': '#ffffff',
        'surface-dim': '#d8dadc',
        'on-surface': '#191c1e',
        'surface': '#f7f9fb',
        'on-surface-variant': '#45464d',
        'on-error-container': '#93000a',
        'surface-container': '#eceef0',
        'error-container': '#ffdad6',
        'on-secondary-container': '#fefcff',
        'tertiary-container': '#0b1c30',
        'secondary': '#0058be',
        'error': '#ba1a1a',
        'primary-fixed': '#dae2fd',
        'outline-variant': '#c6c6cd',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'primary': '#000000',
        'surface-tint': '#565e74',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'on-secondary': '#ffffff',
        'secondary-container': '#2170e4',
        'surface-variant': '#e0e3e5',
        'success': '#2F9E44',
        'warning': '#E67700',
        'danger': '#C92A2A',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
        'gutter': '20px',
        'margin': '32px',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [],
};
